name: Build and Release

on:
  push :
    branches : [ main, develop ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  Build-for-android:
    name: Android build
    runs-on: ubuntu-latest
    env:
      EAS_LOCAL_BUILD_ARTIFACTS_DIR: ./builds/android
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
          expo-version: 5.0.1
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - name: Install deps
        run: npm ci

      - name: Build
        run: |
          mkdir -p ./builds/android
          npx eas-cli build -p android --profile preview --non-interactive --local --clear-cache
          mv ./builds/android/*.apk ./builds/android/Innosoft.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Innosoft-Android
          path: "./builds/android/Innosoft.apk"

  Build-for-ios:
    name: iOS build
    runs-on: macos-latest
    env:
      EAS_LOCAL_BUILD_ARTIFACTS_DIR: ./builds/ios
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
          expo-version: 5.0.1
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - name: Install deps
        run: npm ci

      - name: Build
        run: |
          mkdir -p ./builds/ios
          npx eas-cli build -p ios --profile preview --non-interactive --local --clear-cache
          mv ./builds/ios/*.tar.gz ./builds/ios/Innosoft.tar.gz

      - name: Upload tarball
        uses: actions/upload-artifact@v2
        with:
          name: Innosoft-iOS
          path: ./builds/ios/Innosoft.tar.gz

  Github-release:
    name: Release, build and push to dockerhub using tag version
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ Build-for-android, Build-for-ios ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      
      - name: Download builds
        id: download-builds
        uses: actions/download-artifact@v2
        with:
          path: './builds'
      
      - name: Untar tgz file
        run: |
          tar -xvf ./builds/Innosoft-iOS/Innosoft.tar.gz -C ./builds/Innosoft-iOS/
          mv ./builds/Innosoft-iOS/*.app ./builds/Innosoft-iOS/Innosoft.app

      - name: Conventional Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: 'CHANGELOG.md'
          tag-prefix: 'v'
          release-count: 0
          package-json: './package.json'
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
      
      - name: Upload Apk artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.download-builds.outputs.download-path }}/Innosoft-Android/Innosoft.apk
          asset_name: Innosoft.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload App artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.download-builds.outputs.download-path }}/Innosoft-iOS/Innosoft.app
          asset_name: Innosoft.app
          asset_content_type: application/octet-stream
      
      - name: Sync develop with main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "main"
          destination_branch: "develop"
          pr_title: "Synchronize develop with master after release ${{ steps.changelog.outputs.tag }}"
          pr_body: ":crown:"
          pr_reviewer: "borjar20"
          pr_assignee: "alesancor1"
          pr_label: "auto-pr"                              
          github_token: ${{ secrets.GITHUB_TOKEN }}