name: Expo CI CD

on:
  push :
    branches : [ main, develop ]
  workflow_dispatch:

jobs:
  Build-for-android:
    runs-on: ubuntu-latest
    env:
      EAS_LOCAL_BUILD_ARTIFACTS_DIR: ./builds/android
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
          expo-version: 5.0.1
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - name: Install deps
        run: npm ci

      - name: Build
        run: |
          mkdir -p ./builds/android
          npx eas-cli build -p android --profile preview --non-interactive --local --clear-cache
          rename 's|:|-|g' ./builds/android/*.apk
#         npx eas-cli build -p ios --profile preview --non-interactive --local --clear-cache

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "Innosoft.apk"
          path: "./builds/android/*.apk"